'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class uc_CadastroPC

    '''<summary>
    '''mvPlanoDecontas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mvPlanoDecontas As Global.System.Web.UI.WebControls.MultiView

    '''<summary>
    '''viewListagem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents viewListagem As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''gvPlanoDeContas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvPlanoDeContas As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''viewCadastro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents viewCadastro As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''txtDescricaoPlanoDeContas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDescricaoPlanoDeContas As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbSalvar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbSalvar As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lbCancelar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbCancelar As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''viewConfirmacao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents viewConfirmacao As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''lbConfirmar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbConfirmar As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lbVoltar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbVoltar As Global.System.Web.UI.WebControls.LinkButton
End Class
