'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class CadastroUsuarios

    '''<summary>
    '''lbNovoUsuario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbNovoUsuario As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lbEditUsuario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbEditUsuario As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lbExcluirUsuario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbExcluirUsuario As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lbRecuperarUsuario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbRecuperarUsuario As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''cadastroUsuario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cadastroUsuario As Global.FinanceApp.uc_CadastroUsuario
End Class
